spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "123456"
    url: jdbc:mysql://192.168.1.104/sell?characterEncoding=utf-8&userSSL=false
#    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&userSSL=false
  jpa:
      show-sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    suffix: .ftl
  redis:
    host: 192.168.1.104
    port: 6379
server:
  context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 88ceff948f59e6fa5ece6d3524098998
  openId: oTgZpwU-i3JlkUtvn0oLN0toyAhM
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: /Users/wangxiaoming/Desktop/sell/h5.p12
  notifyUrl: http://nonameming.natapp1.cc/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://nonameming.natapp1.cc
  wechatOpenAuthorize: http://nonameming.natapp1.cc
  sell: http://nonameming.natapp1.cc
